import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises';
import { parseList, parseDetail } from '../lib/crawler/untappd-parser.ts'; import { UntappdCrawler } from '../lib/crawler/untappd.ts'; import type { CrawlDriver } from '../lib/crawler/contracts.ts';
const top = await readFile(new URL('../data/crawler/_fixtures/untappd-top.html', import.meta.url), 'utf8'); const detail = await readFile(new URL('../data/crawler/_fixtures/untappd-detail-info.html', import.meta.url), 'utf8');
test('parses list page', () => assert.equal(parseList(top).length, 5));
test('parses five detail panels', async () => { for (const tab of ['info','ratings','tags','food','similar']) { const html = await readFile(new URL(`../data/crawler/_fixtures/untappd-detail-${tab}.html`, import.meta.url), 'utf8'); const b = parseDetail(html, parseList(top)[0]); assert.equal(b.source, 'untappd'); } });
class Mock implements CrawlDriver { mode = 'http' as const; calls = 0; async fetchPage(url: string) { this.calls++; return { url, html: url.endsWith('/top') ? top : detail, status: 200, retry_after_ms: null }; } async close() {} }
test('limit stops at 2 and concurrency is capped', async () => { const d = new Mock(); const out = []; for await (const b of new UntappdCrawler({ driver: d, opts: { source:'untappd', concurrency:2, limit:2, dry_run:false, resume:true, tag:null, cookies:[], retry_budget:1, output_dir:'/tmp/untappd-test' } }).run()) out.push(b); assert.equal(out.length, 2); assert.equal(d.calls, 3); });
test('dry-run without driver does not call driver', async () => { const out=[]; for await (const b of new UntappdCrawler({ opts: { source:'untappd', concurrency:2, limit:10, dry_run:true, resume:false, tag:null, cookies:[], retry_budget:1, output_dir:'/tmp/x' } }).run()) out.push(b); assert.equal(out.length,0); });
test('detail parser remains usable after failed item', () => { assert.equal(parseDetail(detail, {source_id:'1',name:'x',url:'https://untappd.com/beer/1'}).name, 'Fixture Beer'); });
